name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: '24'
          cache: sbt
      - name: Setup sbt installer
        uses: sbt/setup-sbt@v1.1.12
      - name: check formatting
        run: sbt scalafmtCheck
      - name: run tests
        run: sbt test
